id: A11971490
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
pechas:
- I94FE8EFD
- IED694351
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:51.450486
  last_modified_at: 2023-01-04 12:32:51.450503
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I94FE8EFD/B6D1: A681
  IED694351/3030: A681
